# Generated by Django 5.1.5 on 2025-01-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_telegramuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='User Status'),
        ),
    ]
